// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/guide/index":{"path":"guide","id":"docs/guide/index","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/xiangpeifang/Documents/study/encode-hooks-2.0/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.10.2_@types+node@18.19.122_@types+react@18.2.20_eslint@7.2.0_jest@2_sb7dwmlsqdnbzfdok4baqtlshm/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */'/Users/xiangpeifang/Documents/study/encode-hooks-2.0/.dumi/tmp-production/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/xiangpeifang/Documents/study/encode-hooks-2.0/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.10.2_@types+node@18.19.122_@types+react@18.2.20_eslint@7.2.0_jest@2_sb7dwmlsqdnbzfdok4baqtlshm/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/guide/index': React.lazy(() => import(/* webpackChunkName: "docs__guide__index.md" */'/Users/xiangpeifang/Documents/study/encode-hooks-2.0/docs/guide/index.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/xiangpeifang/Documents/study/encode-hooks-2.0/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/xiangpeifang/Documents/study/encode-hooks-2.0/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.10.2_@types+node@18.19.122_@types+react@18.2.20_eslint@7.2.0_jest@2_sb7dwmlsqdnbzfdok4baqtlshm/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
