// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/xiangpeifang/Documents/study/encode-hooks-2.0/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.10.2_@types+node@18.19.122_@types+react@18.2.20_eslint@7.2.0_jest@2_sb7dwmlsqdnbzfdok4baqtlshm/node_modules/dumi/theme-default/slots/NotFound/index.js';
