// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import nprogress from '/Users/xiangpeifang/Documents/study/encode-hooks-2.0/node_modules/.pnpm/nprogress@0.2.0/node_modules/nprogress';
import './nprogress.css';
import UserLoading from '/Users/xiangpeifang/Documents/study/encode-hooks-2.0/node_modules/.pnpm/dumi@2.4.21_@babel+core@7.10.2_@types+node@18.19.122_@types+react@18.2.20_eslint@7.2.0_jest@2_sb7dwmlsqdnbzfdok4baqtlshm/node_modules/dumi/dist/client/pages/Loading';
import React, { useLayoutEffect, type FC } from 'react';
import { useSiteData } from 'dumi';

const DumiLoading: FC = () => {
  const { setLoading } = useSiteData();

  useLayoutEffect(() => {
    setLoading(true);
    nprogress.start();

    return () => {
      setLoading(false);
      nprogress.done();
    }
  }, []);

  return <UserLoading />
}

export default DumiLoading;
